add arquitecture
fllaryora/MyWeather pull request #1
Opened 2018-04-30 00:36 UTC by fllaryora

2018-05-07 13:32 UTC, lucaslabs requested changes

2018-05-07 13:32 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/data/model/MetaInfo.java
>  public class MetaInfo {
What are possible values of MetaInfo fields?

2018-05-07 13:32 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/data/model/TemperatureInfo.java
>  public class TemperatureInfo {
You have removed min a max temp. Why?

2018-05-07 13:32 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/domain/SearchWeatherInteractor.java
> +    String apiKey = BuildConfig.APP_ID;
Nice!

2018-05-07 13:32 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/ShowWeatherContract.java
> +    void loadWeather(); //called by onResume
Why 2 loadWeather methods?

2018-05-07 13:32 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/presenter/ShowWeatherPresenter.java
> +      symbols.setDecimalSeparator(',');
Magic strings! Extract them into a constant.

2018-05-07 13:32 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +  private TextView city;
use naming conventions for ui fields, like the prefix txt or tv for text view.

2018-05-07 13:32 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherActivity.java
> +        Fragment fragment = fragmentManager.findFragmentByTag(SHOW_WEATHER_TAG);
I believe this can be done on the fragment instead of the activity. I mean getting the user input for the city.

2018-05-07 13:40 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/data/model/TemperatureInfo.java
>  public class TemperatureInfo {
By now I'm not showing that information I will add it again if it necessary in the future.

2018-05-07 13:42 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +  private TextView city;
I will search in google. Do you have some recommendation link inside Material.io or Android web pages?

2018-05-07 13:48 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/data/model/MetaInfo.java
>  public class MetaInfo {
https://openweathermap.org/weather-conditions is the best page that describes all possible states.

2018-05-07 15:30 UTC, ollerandres requested changes

2018-05-07 15:30 UTC, ollerandres commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherActivity.java
> +        FragmentManager fragmentManager = getSupportFragmentManager();
You can create a separate interface to connect fragment with activity. Then, on fragments' onAttach you can check whether activity is implementing your interface.

2018-05-07 15:30 UTC, ollerandres commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +    presenter.attachView(this);
It might be better to `attachView(this)` on `onResume` and `dettachView()` on `onPause` because you are never setting `view = null`. What will happen is that if you go background while the service call is going on, and you never set `view = null` on the presenter, you will be trying to set information on a view that is nonexistent because your app is background sin `isViewAttached` will never be null.

2018-05-09 05:31 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/ShowWeatherContract.java
> +    void loadWeather(); //called by onResume
I delete void loadWeather(); //called by onResume

2018-05-09 05:36 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +    presenter.attachView(this);
Thank you, Andres.

2018-05-09 14:16 UTC, lucaslabs requested changes

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/AndroidManifest.xml
> +            android:name=".presentation.show_weather.view.ShowWeatherActivity"
Nice

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/data/model/SkyDescription.java
> +  @SerializedName("id")
When JSON field name and Class field name are equals there is no need to use SerializedName. Remove it in these cases.

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/data/model/TemperatureInfo.java
> +  private double minimalTemperature;
minimum and maximum are proper names.

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/data/utils/Constant.java
> +public class Constant {
Nice

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/presenter/ShowWeatherPresenter.java
> +    String query = parameters.get(Constant.API_PARAMETER_QUERY);
Why a map if you will pass a simple String as a parameter?

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/presenter/ShowWeatherPresenter.java
> +    if (model.getSkyDescription() != null && model.getSkyDescription().size() > 0) {
Just do a null check for model, not every single value.

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/presenter/ShowWeatherPresenter.java
> +      DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.getDefault());
Create a separated method to format the values.

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +  ShowWeatherPresenter presenter;
Add private keyword.

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +        .setText(uiModel.getMaxTemperatureLabel() + " " + getString(R.string.degrees_celsius));
Magic string! Use String.format method for this purpose and create a constant for white space.

2018-05-09 14:16 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +      Snackbar.make(showWeatherView, "Cannot load the weather", Snackbar.LENGTH_LONG).show();
Magic string! Extract this string into a resource file.

2018-05-11 04:51 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/data/model/SkyDescription.java
> +  @SerializedName("id")
done

2018-05-11 05:01 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/presenter/ShowWeatherPresenter.java
> +      DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.getDefault());
done

2018-05-11 05:02 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +  ShowWeatherPresenter presenter;
done

2018-05-11 05:02 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +        .setText(uiModel.getMaxTemperatureLabel() + " " + getString(R.string.degrees_celsius));
done

2018-05-11 05:05 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +      Snackbar.make(showWeatherView, "Cannot load the weather", Snackbar.LENGTH_LONG).show();
done

2018-05-14 13:51 UTC, lucaslabs requested changes

2018-05-14 13:51 UTC, lucaslabs commented on app/build.gradle
> +    compile 'org.jsoup:jsoup:1.10.2'
What for this jsoup lib?

2018-05-14 13:51 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/ShowWeatherContract.java
> +    void stopRefreshing(boolean showEmpty);
What's the idea of `showEmpty`?

2018-05-14 13:51 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/presenter/ShowWeatherPresenter.java
> +        view.showError("Invalid Query");
Magic string! Extract this string into a resource string.

2018-05-14 13:51 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +public class ShowWeatherFragment extends Fragment implements ShowWeatherContract.View {
Format this class, the `{` needs to be at same line of class name, this is line 35.

2018-05-15 00:49 UTC, fllaryora commented on app/build.gradle
> +    compile 'org.jsoup:jsoup:1.10.2'
I used to use jsoup for parsing HTML

2018-05-15 01:12 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/presenter/ShowWeatherPresenter.java
> +        view.showError("Invalid Query");
I took the string to the constant class because the presenter doesn't have access to "getString()".

2018-05-15 01:28 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/ShowWeatherContract.java
> +    void stopRefreshing(boolean showEmpty);
I quit showEmpty. The idea was using it after unhappy paths.
I regret because It doesn't worth changing the view when you are showing an error message.

2018-05-15 01:38 UTC, fllaryora commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +public class ShowWeatherFragment extends Fragment implements ShowWeatherContract.View {
I indented the class.
 The curly bracket has already been in the same horizontal line that the class names.  I don't understand you.

2018-05-15 01:38 UTC, fllaryora commented on app/build.gradle
> +    compile 'org.jsoup:jsoup:1.10.2'
I quit it.

2018-05-16 16:51 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/presenter/ShowWeatherPresenter.java
> +        view.showError("Invalid Query");
Create a method on the view/fragment to return the desired string, then you can call that method in the presenter just like `view.showMyString(view.getMyString())`.

2018-05-16 16:52 UTC, lucaslabs commented on app/src/main/java/training/globant/myweather/presentation/show_weather/view/ShowWeatherFragment.java
> +public class ShowWeatherFragment extends Fragment implements ShowWeatherContract.View {
it's ok.

2018-05-16 16:52 UTC, lucaslabs commented on app/build.gradle
> +    compile 'org.jsoup:jsoup:1.10.2'
cool, we are not parson any HTML code.

2018-05-16 18:05 UTC, lucaslabs approved these changes

2018-05-18 02:20 UTC, merged